name: CI


on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 
            - name: Install requirements
              run: pip install -r requirements.txt
            - name: Run flake8
              run: flake8 .
    test:
        runs-on: ubuntu-latest
        needs:
        - lint
        steps:
            - uses: actions/checkout@v4.2.2
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 
            - name: Install requirements
              run: pip install -r requirements.txt
            - name: Run tests
              run: python -m unittest -v tests.user_model_test
